# NOTES FOR YOU PEOPLE:
# a = Atlas (for when he speaks directly)
# g = Game (a message from the game directly to the player)
# l = Luna (for when Luna speaks directly)
# q = ??? (for when an unknown speaker speaks)
# No letter assigned: (internal dialogue, like thinking, or narration)
# In addition, before Atlas gains his name, he will speak in \"*insert text here\"

# DAY ONE

"The soft sound of ocean waves hitting the soft shore was the first thing I remembered."
"The next thing I remembered was the soft, warm, and bright rays of sunshine on my face, waking me from my gentle sleep."
"That's about all I could remember. Besides that, my mind was clear, I couldn't recall my age, name, or anything like that."
"\"Where am I? What is this place?\""
"My eyes slowly opened and greeted the bedroom I was in."
"\"Oh, this is…\""
"Not a place I was familiar with."
"Everything here was foreign to me... but I was overcome with a strange feeling of Deja Vu, like I've been here before."
"\"Who am I? Why can't I remember a single thing? Where is this place?\""
"I pointed at the window in front of me."
"\"Well, clearly that's a window, and those are curtains over the edges.\""
"Next, I pointed at the wall."
"That's a poster for some kind of rock band."
"How come I knew what everything in this room was, yet nothing about myself?"
"I know what these things are, but I still can't remember where they come from..."
"I couldn't put this feeling into words. It was like when you got lost in the woods, where you knew that there were trees everywhere, but you still couldn't figure your way out."
"I didn't even know what I looked like. Maybe I had dark hair, maybe it was light."
"Maybe that was a bit of an exaggeration, maybe I was just a bit in shock."
"I focused as hard as I could, trying to muster up a single ounce of knowledge about myself."
"..."
"Nope, nothing."
"Well, I guess I can at least figure out my hair color."
"I pulled down my hair, which although was short, was long enough for me to look at."
"..."
"Well, turns out I have brown hair. Guess that's at least a place to start."
"I glanced across from my bed, and noticed a mirror hanging on the wall next to the closet."
"Curious to see what I looked like, I slowly lifted myself out of bed, my muscles stiff like I just woke up from a deep sleep."
"..."
"Well, I guess this is what I look like."
"I was greeted by emerald eyes, dark skin, and brown hair. I don't really know what I expected, but it sort of surprised me to see how plain I looked."
"I just looked like any average guy that you might run into on the street."
"I felt like an outsider looking through someone else's eyes through this mirror, like this body wasn't mine."
"I mean, clearly, this was my face. After all, I'm looking at it, aren't I?"
"Still, I felt like a stranger, as I had no idea who this person I was looking at was. Was he a nice guy? Or was he a criminal?"
"Thinking about who I truly was made me a bit light-headed and dizzy, so I decided to stop. Instead, I tried to think about where I was."
"\"What's outside the bedroom? Where am I?\""
"I asked the question out loud, like I was waiting for someone to answer me."
"..."
"There was no answer."
"All there came was the sound of the ocean waves gently pulling and pushing, gently echoing against the walls of my room."
"Well, I can at least say, I am as clueless about this place as I was about myself."
"It's almost like I was a character from a video game, TV show, or something like that."
"In fact, it's script perfect actually."
"Step one: wake up in a foreign land. Check."
"Step two: have amnesia. Check."
"Step three: get magic powers, and find a hot girl. Uh... not check."
"Well, I suppose it's not {b}quite{/b} script perfect. But at least most of the steps are complete. After all, Rome wasn't built in a day."
"Still, I felt more like an NPC, or a side character at the moment, rather than being the charming and daring protagonist."
"But if I really was a side character..."
"Where is everyone else? Maybe someone here knows about me, and could lend me a hand or two."
"You know... this place is starting to have a musty smell to it. It's getting hard to breathe, I don't want to stick around for long."
"Some fresh air would be nice, and if I'm gonna try to find anyone, they're probably not gonna show up in my bedroom."
"I stretched out a bit, feeling my muscles relax from the stiffness I had earlier. After that, I walked out the door at the corner of the room, and found myself in what looked like a town square."
"The soft sounds of the ocean waves hitting the shore I heard in the room became clearer, like a pair of misty glasses getting wiped."
"The gentle sound of the waves and the gentle wind blowing onto my face was certainly relaxing, but I still felt just as confused as I was before."
"I took a few glances around the town square. The town square was empty, not a single person was in sight."
"The sounds of the ocean and the wind became hollow, as if there was something missing. The comfort I once felt with them became a deathly silence, trying to pull me into an abyss."
"I called out into the town square, becoming desperate for any response."
"\"Hello?\""
"..."
"Once again, I was only answered by more silence."
"The road itself wasn't very fancy, it would just have been like any old street you'd see on the street."
"Still, with no one here... it raises a pretty big red flag."
"If no one was here, who was keeping it in this good condition?"
"Puzzled, I went to look for more answers, moving on further away from the town square, to a nearby spot of greenery west of the square."
"The mere sight of the garden was a marvel in itself. It was beautifully grown, a ring of blooming roses and daisies surrounded a tall oak tree, and an adorned gazebo lay at the middle of the garden."
"Still curious to find anyone, I walked closer to the gazebo, taking a closer look at it. It was clean, but upon closer look..."
"There was a thin layer of dust on the floor of the gazebo, almost like the first flakes of snow on a cold winter morning."
"Chances are, no one's been here either, since this dust hasn't been disturbed in a while."
"*sighs*"
"\"What kind of place is this?\""
"\"I just want to find someone, anyone!\""
"\"Not only is there no one here, I'm lost as all fuck!\""
"\"Who the hell am I?!\""
"I shouted that question to the skies, who just as before, answered me with apathy."
"Frustrated, I headed back to the town square, tired and confused by the situation I was in."
"Maybe I took a wrong turn, but it wasn't the town square that I ended up."
"Am I... at a beach...?"
"Is this town... on the coast? Or maybe... it was an island?"
"I looked around me, and the beach stretched far beyond what I could see, like the horizon."
"I gazed upon the waters, to see if there was any kind of land I could spot."
"All that greeted me was the line that the sky touched the water, no land in sight."
"Still confused by how I ended up on the shore instead of the town square, I was about to turn back so I could head to back, until I saw what appeared to be a silhouette of someone on the sand."
"There appears to be someone here."
"A girl, I think. Noticing me, she turned towards me and stared at me."
q"..."
"I couldn't tell her age."
"She could've been anywhere from 14 to 25."
"She had a look of both maturity and youth to herself."
"\"Hey um... so...\""
q"..."
"Thinking that maybe she hadn't heard me, I tried asking again."
"\"Hey, it's nice to meet you-\""
q"Shut up."
"\"W-W-What..?\""
q"If I didn't answer you the first time, what made you think I'd answer you the second time? Have you got a single brain cell up there?"
"She sighed."
q"It doesn't matter."
"She turned and walked off, her footprints slowly being wiped away by the waves."
"As she took a few steps, she turned around towards me."
q"You. Come. Don't make me repeat myself, alright?"
"Honestly, she sort of bugged me and came off as bratty, but she's probably the best chance I have of learning what was going on with the town."
"I followed her as she walked on the shoreline, just far enough from the waves to stay dry."
"The tension in the air felt so tight I felt as if I could choke on it. Trying to break the tension, I tried to make small talk with her."
"\"I know we got off at the wrong end, but my name is... it's... uh...\""
"I completely forgot about the fact I forgot my name, I made a huge mistake."
"\"I mean, it's nice to meet you. What's your name?\""
q"..."
"Her silence got her message through to me, like an arrow piercing through flesh. She didn't want to talk to me, that was for sure."
"I decided to just give up for now, and continue following her around the shore, the two of us walking in complete silence."
"As we walked on the shore line, I began to notice more about this place I was in."
"The shoreline wrapped around the town in a circle. It looks like I was right earlier, it really is an island."
"The island wasn't particulary big, but was able to accomodate a town, and that was about it. It didn't look like there was anything other than the town on the island."\
"Besides my room, the town square, and the garden, there was quite a bit more on the town I didn't pass through."
"There was what looked like a library, a forest, and a lot more buildings and streets. I tried to identify them, but the girl walked very quickly, and I only got small glimpses of everything else."
"Once we made a full loop around the island, I decided that it was time to ask her another question, even though she was cold towards me earlier."
"\"Say, have you seen anyone else on this island, or has it been just us two?\""
"I expected her to respond to me with silence, and a stare, but instead, she asked me her own question."
q"What do {i}you{/i} think about this island?"
"Maybe she was answering my question, or maybe she was just ignoring me, but I was still confused on how to answer her."
"I honestly had no idea what to say, but I feel like she wouldn't be too happy with me if I started questioning her. But since this might be my only chance to get anything out of her, I just rattled off what was on the top of my head."
"\"You know... I was going to ask you that question. I'm completely clueless about anything on this island. In fact, I don't even know anything about myself.\""
"\"I think I have amnesia or something, but I feel like everything is all just trapped inside me. Matter of fact, I guess you could say I'm on my own island, one inside of my head.\""
"I didn't know where this weird poetic talk came from, but I just went with it."
"\"My name... my age... everything... it's on the mainland, but all I can see is the empty horizon. I can't even be sure if there is anything beyond that horizon, or where that mainland is.\""
q"..."
"She didn't even answer me with any response or follow-up question. Instead, she turned away from me, and gazed into the ocean, like she was lost in thought."
"I decided to do as she did, and also gazed into the ocean. But unlike her, I didn't see what was so special about it."
"It was such a plain scene, every inch of the ocean looked the same, but we stood like that for minutes, maybe hours, I lost track of time."
"Suddenly, she turned away, and continued walking."
q"You. Come."
"I made small comments, and occasionally asked questions. Normally, she would just ignore them, but rarely she'd answer them, or make her own small comment."
"They were as superficial as you could get, and I didn't really get much information out of her about the island, or herself."
"For example, when I asked, \"Small island, huh?\" she just replied with a brief, \"Yeah.\" and continued walking, like she was completely uninterested."
"By the time we finished our second loop around the island, the sunset had finally faded away, and the moonlight reflected onto the sand."
"She turned towards me, and spoke gently, but also firmly."
q"Hm. So it's night time. Thanks, stranger, for this meaningless time. Farewell."
"She turned towards the lights of the town square, and was about to leave, until I caught her attention."
"\"Wait, before you go, let me ask you someting.\""
q"..."
"She responded with the same deathly silence. I could feel the tension build up, as sharp as a knife."
"Regardless, I still mustered up the courage to ask her:"
"\"What's... your name?\""
"She looked at me in surprise, as if she wasn't expecting me to ask her that question."
"For the first time, she showed to me a sign of herself, a more sensitive side. But I could see joy in her eyes, glimmering with the moon's light."
"She looked into the night sky, and stared. I looked up as well."
"The sky glistened with stars, seemingly covering us in a blanket of light, almost like they were smiling at us. It was breathtakingly beautiful."
q"So you asked me what my name was? I'm..." 
"Luna. Call me Luna, I think it's... fitting. Now then, what's your name? I believe you stopped before you told me your name earlier."
"I looked down from the night sky, into the sand. It was all so... empty."
"This island, it was... empty. Everything felt hollow, and I didn't know why. Maybe it was the silence, or the loneliness, but..."
"Just like the sand, everything was just a blur, it all looked the same and felt the same. I felt just like another grain of sand."
"Would it make a difference if that grain of sand was gone? Probably not."
"On this island, we were likely alone, just Luna and me, on this deserted place."
"There was no one esle, no one here for me to depend on, and no one for Luna to depend on."
"Except for each other. We could be... lonely together."
"I raised my eyes back up towards the sky, still glistening bright with stars, surrounding the moon."
"We were going to need each other to survive. For Luna, I wanted to be her everything, I wanted to be the earth that held up her night sky."
"I answered her:"
a"Atlas. My name is Atlas."
"I knew that I screwed it up badly, it was a terrible answer. Still, she seemed to understand what I meant, but didn't show any signs of it."
"Except for a small glimpse of a smile on her face. I blinked, and it was gone."
"She asked me another question:"
l"So, Atlas, when can I see you again?"
a"I... I don't really know, but... I promise that I'll be here tomorrow, as early as possible."
l"Ok."
"She simply nodded, turned, and leaved. Honestly, I wanted to ask another question, but when I turned around, all I saw were light footprints in the sand."
"The gentle night wind laid a light blanket of sand over the footprints, and the beach turned pristine once again, like she'd never been there."
"I felt the land breeze, like a gentle push for me to reach closer to the sea. I made my way closer to the edge of the shore, but..."
"I realised how tired I was. Even though I hadn't really done anything all day, my body ached, and begged to go to sleep."
"Tired, I made my to the garden, so I could go back to my room."
"In the night time, the flowers looked even more pretty, shining from the moonlight."
"I looked at the gazebo, and the layer of dust caught my eye again. I saw light footsteps on the wood floor. There was no ocean to wipe away the footprints."
"It wasn't a dream. She was real. I wasn't really alone here."
"Slowly, I began to feel a warmth in my body, each heartbeat spreading the warmth further into my body."
"I fell to my knees, and a small tear rolled from my eye, and hit the floor. With each tear, another followed... and after that, yet another."
"Small teardrops became a stream of tears. It might've been the relief I felt, but every teardrop felt like another weight lifted from my shoulders."
"At last, after kneeling for I don't know how long, I finally stopped crying, and I carried myself back to my room, mentally weary and tired."
"Unable to lift myself out, I felt myself sink into the bed, and I slowly began to feel everything become a blur, and I fell asleep."
"..."
"..."
q"Atlas..."
"..."
a"Hngh...? What's... what's going on...?"
"I opened my eyes, but all I saw instead of black, was a blur of green, it sort of reminded me of the forest."
a"What...? Where am I? Who's speaking to me? Show yourself!"
"..."
a"Confused and disoriented, I felt my heart begin to race, my palms getting sweatier and sweatier, my body beginning to tremble."
q"Do not be afraid, Atlas. You will be safe here. Come, I have much to tell you, child."
"The voice was soft and gentle, the same way a mother would comfort her daughter. It was nothing like the brash and direct way Luna spoke."
"Still, it didn't help that I still had no idea where I was, or who was talking to me. Nonetheless, I turned to try to face where the voice was coming from."
"..."
"Here, Atlas... don't worry."
"The voice that spoke appeared in front of me, materializing in front of the blur."
"Yet still, I couldn't make what the voice looked like, but I could tell that she was wearing some kind of dress, the rest of her body was just as blurred as the area around me."
a"Who are you, and where am I? Where's the island? How do know my name?"
q"The island... you haven't left the island, Atlas. We're on the island as we speak. I'm afraid I cannot tell you who I am, or why I know your name. Not yet."
a"W-W-What's going on then? This doesn't look like the island!"
q"You're right... Atlas. Do not fear, and do not hesitate, I am not here to hurt you."
q"The island I speak of is not the one which you and the girl live on. No, this is..."
"She paused for a second, before finishing her sentence."
q"I'm afraid I cannot tell you that either, but you will find out in time, do not be worried."
"A million thoughts rushed through my head. Who was this woman, and how did she know my name? And how did I end up here?"
"I looked around me once again, only to find a blur of green. But... where's Luna then? What happened to her? Was she safe?"
"I wanted to ask, but I knew that if I did, all I'd get is probably \"I cannot tell you that yet\" as an answer, so I decided to get as much as I could out of this strange woman."
a"Well, if you can't tell me all these things, then why am I here?"
q"I am here to help you, Atlas."
a"How could you possibly be helping me, when you won't tell me what's going on?"
q"Do not lose patience, Atlas. I am here to deliver you a message, do not take my word for granted."
a"..."
q"Beware of the prison of gold, but love the heart of blue, and you will break through to find the past of the ones you walked along the road with."
a"What is that even supposed to-"
q"The link between us is still weak, we do not have much time. Do not forget my message, and we will meet again."
"As she cut me off, a bright flash began to appear from her body, getting so bright that even the colors of green faded into the whiteness."
"Then as all became white, I closed my eyes to shield myself from the blinding light."
"..."
"I began to feel a warm feeling on my eyes, slowly spreading across my entire face, and then my chest, then slowly reaching throughout my entire body."
"I opened my eyes..."
"And found myself back in my room, flooded by the morning light shining through the window."
"..."
a"Was that all just a dream...? How weird. But what did that woman mean?"
a"\"Beware of the prison of gold, but love the heart of blue, and you will break through to find the past of the ones you walked along the road with.\""
a"..."
"Being on this island without my memory is already weird enough, I don't need anything else making this whole situation more confusing."
"So, I decided to just stop putting my mind on it, and just focus on what I had to do at the moment. And that would be..."
"..."
"I glanced outside the window, remembering the bright light that woke me up from that dream."
a"Wait, hold on, am I forgetting something?"
a"..."
a"Wait! I just remembered! I promised I would meet Luna first thing in the morning!"
"Oh god, what time was it? I looked outside back at the window, trying to guess what time it was based on where the sun was."
"The sun was almost completely out of view from where the window was... which meant... It was almost noon?!"
"My heart skipped a beat, and I jumped out of bed, realising how late I was."
a"Shit! I need to get to the beach {b}now{/b}!"
"I ran to the closet, threw open the doors, and randomly threw picked out a t-shirt and jeans."
"I rushed to the mirror, to get changed."
a"Shit, shit, shit! Hurry!"
"I threw yesterday's clothes onto the bed without even folding my clothes, and sprinted down the stairs and out the door, to the beach."
"..."
"She's just staring at me, emotionless. Is she... mad at me?"
a"Hey Luna! Good morning, how are yo-"
l"You're late."
a"Yeah... sorry about that-"
l"You overslept, didn't you?"
a"Huh? How did you know that?"
l"Easy. Your hair's a mess, and you haven't even changed since yesterday. Besides, why else would you be late? It's not like there's anything else to do on the island."
"I sighed."
a"You're right. I overslept, I'm sorry alright?"
l"No."
a"Huh?"
l"It's not alright, if you wanted to give off any sense of basic decency, you'd be here at least an hour before you're supposed to arrive."
a"W-W-W-What?! An hour?! You're joking, right?"
l"Why would I be joking? It only makes sense for you to show up on time if you want to leave a good impression on someone."
a"But you wanted me to show up an hour early? I can't even imagine showing up that early! Wait, hold on..."
a"Does that mean you've been waiting for me the whole morning?"
l"..."
a"Oh... you have, haven't you?"
"Well, she probably shouldn't have been waiting for me that early in the morning, but still..."
"She blushed a little bit, before regaining her composure."
l"It doesn't really matter. I'm going to tell you something, keep it a secret alright? I don't want anyone else to find out."
a"Is there even anyone else for me to tell?"
"She glared at me, her eyes buring with a furious rage, looking deep into my soul."
a"I-I-I mean... please do go on, what did you want to tell me, Luna?"
"She sighed."
l"Well you've probably already figured this out already, but I'm the same as you."
a"Same as me? How?"
l"Do I have to explain {b}everything{/b} to you? I don't have any memory of my life or who I am. It's that simple."
a"So... you don't know where we are either?"
l"Yeah, this island is as confusing as it is to me as it is to you. But unlike you, I have an idea of where I'm going."
a"Hey! What's that supposed to mean?"
"She completely ignored my question."
l"Follow me, I'll show you around the island. Don't get lost, okay?"
"She walked off the beach, and towards the garden."
l"Judging by the footprints you left behind, you've already been here, but this is the garden. As you can see, there's a gazebo, and a bunch of flowers."
"She pointed outwards from the garden into the forest behind the flowers."
l"Hurry up, or else I'll leave you behind."
a"Oh... Okay..."
"She rolled her eyes, as if she was bored out of her mind for being here."
l"And this is... the forest. I don't know what to explain, but in case you're a forest fan, here you go."
"I glanced in between the trees, and I saw a glimpse of a sandy beach."
a"Does the forest connect to the beach?"
"She stared at me in surprise."
l"It does?"
"She pushed past me and stood at the edge of the forest. I followed her and got a clearer view of the beach."
"It looked like we were on some kind of cliff that connected to the beach, about 75 feet up if I guessed."
"Luna regained her composure quickly, the look of shcok on her face quickly replaced by one of smugness."
l"Of course you'd follow me, such a simple observation, and yet you seriously believed that I didn't already know that? My, I must say you're not as bright as I thought."
a"W-W-Wait, what?! You're kidding right? How stupid do you think I am? Hey! Answer me!"
l"Moving on."
"She completely ignored me, and instead headed back towards the garden, a smug smirk on her face the entire time."
l"As you can probably tell, unless I'm mistaken, we're once again back at the garden."
a"So... what was the point of going through the forest, you could've just told me where the forest was, there's a path leading to it!"
l"Hm, yes, it appears like such. That was one of the roads, this is the important one."
"She pointed towards the other path, which led to the town square."
l"Let's go."
a"Hey... Luna?"
l"What is it, I don't have all day, you know?"
a"It's just... do you really know where you're going? I feel like you didn't know where the forest was..."
"She struck a quick glare at me before regaining her composure to her usual annoying and confusing self."
l"Why, of course I did, it's not my fault you're too stupid to catch onto what I'm doing, it's very simple."
a"You're just guiding me around the island, right? What else is there to do?"
l"Well, maybe you'll figure it out when we head towards the town square."
"Wait, town square? She knows where the town square is, yet it felt like she was lost at the forest. Is there really some deeper meaning?"
"Or is she just messing with me?"
l"It was a mistake to bring you along. Hurry up or I'll leave you here alone, go deal with everything on your own, I'm out."
a"W-W-W-Wait!"
l"Tch."
"She walked off briskly, intentionally trying to leave me behind. Not wanting to lose her, I sprinted after her."
a"Hold on, I'm coming!"
l"Took you long enough, how slow are you?"
a"*muttering* Slow? I'll show you slow, you stupid c-"
l"I'm sorry, did I hear something from you, or was that the wind?"
a"N-N-No! It was nothing!"
l"Good, that's what I thought. Anyways, welcome to the town square, I'm guessing you know where this is, because you live here."
a"Huh? How did you know that?"
l"How did I know that? Jeez... what's going up in that empty hole of a head you have... look up, genius."
"I did as she asked, and looked up, towards my room, which sat on ground level around the fountain."
l"If you payed any small amount of attention, you'd see that's the only building with its lights on. There's no reason for it to be on, unless someone turned it on, right?"
l"And if no one else is on this island except for us... then that means you must've turned them on. The only reason you'd do that, is if you frequent the place, so... your house."
a"I mean... I guess you're right. I've never really thought about that. Huh."
"She grabbed me by the sleeve of my shirt, and suddenly pulled me to her, her face red with anger."
a"Luna! What the fuck are you doing?! Let me go! Hey! Are you even listening to me?!"
l"\"I don't know\", that's all you've been saying this whole time! Do you think I'd be fond of hearing the same thing over and over again?!"
a"..."
a"...Sorry...?"
"She let out a sigh of relief, and let me go."
l"It's of no matter, I apologize for my conduct. But don't think that means you've got on my good side."
"Damn... she's so hostile."
"Wait... what did she say earlier?"
l"And if no one else is on this island except for us... then that means you must've turned them on."
"How can be so sure of that? Could there really be no chance that there's someone else here?"
a"Hey... Luna? Do you really think we're the only people on this island?"
l"Of course I do! I know this place like the back of my hand, do you really think there's anyone else here? The only other living things here are plants."
a"No, I meant like... do you think there's someone watching us?"
l"Like in a movie?"
"She snorted and broke out into a giggle."
a"..."
l"Oh... you're not joking. Well... a queen does need a jester. Carry on then, court fool."
a"Court fool?"
"She shot a icy cold glare at me, and I felt my heart skip a beat."
a"I mean... do you think someone masterminded this? There's no way the two of us could have just ended up here randomly."
l"Really? Then how do you think this supposed mastermind is controlling us? I don't believe I've ever seen you for a moment in my life, even without my memory. Why would this mastermind put two strangers onto a deserted island town?"
l"No... you're right. There's got to be a meaning behind this."
"Luna began to stare off into space again, deep in thought."
"My mind flickered back to the dream I had last night, with the green woman."
q"Do not be afraid, Atlas. You will be safe here. Come, I have much to tell you, child."
"She called me child, like she knew me. Could she be someone that I know... is she on this island? Maybe she knows Luna too?"
"I looked back at Luna, who was staring off into space, looking like she had just forgotten the conversation we just had."
"Plus... even if I told her, I feel like she'd just laugh at me, and then say some insult before moving onto another topic."
a"Uhm... yeah, it's nothing, Luna. Don't worry, it was just a random thought. Let's move on."
"She muttered under her breath."
l"Sure didn't sound like nothing..."
a"Huh? Excuse me?"
"Just as expected, Luna instantly snapped back at me full force, almost as if she was expecting it the whole time."
l"I'm sorry, were you raised in a barn? Who ever said that you can just listen in on other people?! Some nerve do you have!"
a"S-S-S-Sorry! Can we move on?"
"Even when she calmed down, she still looked miffed, though honestly, that might've just been her normal face."
l"Fine, I'm sorry, alright? I didn't mean to snap like that..."
a"Did you just-"
l"Yes. Now shut up before I take it back."
a"O-O-Okay."
l"The next area that we're gonna check out is the shopping district over there."
"She pointed at the road just across from us, the one that was just past my house."
a"That's just... an ordinary road."
l"No, you idiot! What's on the road, not the road itself!"
a"Calm down, I was just joking, alright?"
l"Huh? Joking?"
"For just an instant, I saw her blush, a light red spreading across her cheeks."
"But, she quickly regained her composure, and looked just as annoyed as before."
l"That... That wasn't very funny. Stop that..."
a"Oh ho? What's that? I didn't hear you, mind speaking up a bit?"
l"Tch. Don't think you're getting anywhere, Atlas. I'm taking back what I just said."
a"Oh come on! Don't be such a grouch!"
l"Whatever, I don't even care anymore, follow me if you want, or don't. It's the same to me."
a"Stop going so fast! Wait up!"
l"Looks like you still decided to follow me, very well. Welcome to the shopping district."
"The entire street was packed inch-to-inch with clothing stores, restaurants, and various other shops."
"Just as you'd expect, the entire street was still empty of all life, except for Luna and me, I guess."
l"As you've probably noticed by now, there's no one here, and all the lights are off too."
a"Just like the rest of the island, right?"
l"Yeah, it looks like our earlier theory is becoming increasingly valid."
a"Hey Luna... do you mind if I ask you a question?"
l"Fine."
"It wasn't really an invitation, but with Luna, there's honestly no telling what's okay with her."
a"It's just... how are you so sure that there's no one else here?"
l"I'm not."
a"Huh? But didn't you say that a second ago?"
"Once again, my mind flickered back to the dream I had last night."
a"I mean... if we're here, and we don't have our memories, it can't all just be a huge coincidence, right?"
"Unlike last time, she didn't laugh at me. Instead, she looked deep in thought, considering the question."
l"I suppose that's true. But then, let me ask you, where is this mystery person right now? That's what you were thinking about earlier, wasn't it?"
a"Uh... yeah, that's right. But do you think... they have some kind of reason for throwing us onto this island? Like maybe... they have some kind of grudge against us?"
l"Grudge? No... I don't believe that's it... it's {b}nature{/b}."
a"Nature?"
l"Atlas, have you ever heard of a man named Jean-Jacques Rosseau?"
a"Rosseau? No... I have no clue. Wasn't he like... some French dude?"
l"Well, I  guess you could call him that. Yes, he was \"The French Dude\"."
l"Actually, he was Swiss, but that's not important. Rosseau was known for his philosophy, about the wild man."
a"So like... a cave man?"
l"Sort of, but more akin to a feral man. He believed that the man, unhindered by society and laws, was the most kindest and happiest form of man."
l"Essentially, he believed that society, although inevitable, was the reason why the faults of mankind arose, and the more ignorant of modernization, the happier we were."
l"That sounds quite familiar, doesn't it?"
a"It's just like... this island, isn't it?"
l"Looks like there's something up there that isn't just empty space, good job."
a"So what you're saying... is that someone kidnapped us... and then wiped our memories so that we could become \"pure\" or something? I'm not gonna lie, but that sounds pretty far fetched."
l"To me, being on this island with someone like you already sounds far fetched, isn't it? I was kidding anyways, that would be ridiculous. How on Earth can you wipe someone's memories?"
a"You were... joking? That wasn't very funny, y'know."
l"Neither was yours, and you didn't hear me object. Now quit your jest, and let's move on, or else you'll really be a court fool."
a"Tch. Where are you taking me now?"
l"Back the other way, towards the forest."
"I noticed that there was still more to the end of the street, a faint golden building in the back, along with what looked like a fire station in the back."
a"Huh? What about that thing at the end of the street?"
l"I haven't actually investigated that area, we'll go some other time. It's probably not that important. Let's go."
a"Um... sure, I guess. If you really say so, then sure."
a"Well... this is the forest. I don't know why you took me back here, but..."
l"This way, we're not heading back to the cliff."
a"Alright, alright. You don't have to nag me all the time, jeez."
l"In that case, you can stop following me anytime you wish. It would be one less burden to deal with, aside from my memory, and getting off this place."
a"..."
l"Oh? Then I suppose you must have to deal with my nagging then. Hurry up, we're almost there."
a"This is just a bunch of trees, do you even know where you're going?"
l"Maybe not, but certainly a lot more than you do."
a"Does that mean you don't know where you're going?"
"She snapped back at me, full force as always. At this point, I don't even know why I still bothered."
l"Of course I do! Shut up! We're here!"
a"This is..."
l"I know what you're thinking. It's not a church. It's a library-"
a"I wasn't going to say that!"
"She glared at me, her icy stare breaking into my spirit as usual."
a"Okay... maybe I did, uh... sorry for interupting you, carry... on?"
l"As I was saying, we'll come back here tomorrow, I'm done for today."
a"Huh? Done for today? But it's only around noon!"
l"Well being with {b}you{/b} has made it feel a lot more like a week than a few hours. I'm tired, and I'm going home to take a nap. Screw off."
a"Fine, well I'll go check out the library by myself anyways, I don't need you!"
l"No, don't."
a"Oh ho ho! Trying to boss me around now, aren't you? Well guess what? I think I'll go in there anyways!"
l"I said don't do it."
a"Why should I listen to you, heh?"
"Without any warning, she completely exploded in anger, her cold and icy personality immediately melted by an explosive anger."
l"I SAID DON'T! WHY CAN'T YOU JUST LISTEN TO ME FOR ONCE, YOU BRAINDEAD PIECE OF SHIT?! GET OUT OF MY FACE!"
a"Woah! I-I-I'm sorry!"
l"SORRY FOR WHAT?! THAT'S ALL YOU CAN SAY! YOU DON'T FUCKING LEARN! JUST GET OUT ALREADY! GO TO YOUR STUPID LIBRARY, I DON'T CARE ANYMORE!"
a"Fine! Fine! Fine! I won't go! Please calm down!"
"Almost as quickly as she exploded, the whites returned to her face, and she once again returned to her cold exterior."
l"Good. Now if you're done, I'll be going home for a nice shower and a nap, bye."
a"Wait, hold on a second!"
l"What is it? Can't you just leave me alone for once?"
a"You saw my house, let me see yours!"
l"I... don't want to."
"Knowing how she just exploded, I honestly didn't feel like pressing on her was a smart idea. So, learning from last time, I chose to not."
l"It probably won't do any good if either of us lose our temper like that, so I'm genuinely sorry about that. I just didn't want you to see the library yet."
a"I'm sorry too, for being so stubborn. But... don't you think that it would be better if we got to know each other better, if it's just the two of us here?"
l"How do you expect to do that, genius? We both have no memories."
a"Well... you could start by showing me your house."
"She exhaled heavily."
l"Fine. It's on the beach, follow me. I guess that nap and shower will have to wait."
"With her leading, we walked back to the beach, the same spot I met her on yesterday."
a"Uh... I don't see any house around here, but that might just be me."
l"It's around the bend, don't be so idiotic, alright?"
a"Yeah, yeah... whatever."
"Just like yesterday, we walked around the beach, but this time, under the hot afternoon sun."
l"Welcome to my house, are you happy now? It would be nice if you left now."
"I looked up, and noticed a low round door built into the side of a cliff, the same one that Luna and I were on at the forest, though I guess because it was angled inwards, I didn't get to see the door."
a"Hey that's... the cliff we were on earlier, isn't it?"
l"Well, it looks that way. Answer my question, are you happy now? Are you going to leave yet?"
a"Oh, come on! Can't I take a look in there? It's not like there's anything... private... in there, right?"
"Knowing how she'd react, it was a bit of a gamble if she'd explode at me or not. Still, I winked at her to really hit in the nail."
"Her face light up in bright red, and the look of shock on her face was priceless. For the first time, she actually looked embarrassed."
l"O-O-Of course not! W-W-What kind of person do you think I am, huh?! I-I'll kill you!"
"Bingo."
l"F-F-F-Fine, go s-see for yourself, there's nothing wrong in there, y-you c-creep! God, I hate you..."
a"Well, well, well. Ladies first."
l"H-H-Hell no! L-L-Look at that low door! You want to take a peek, d-d-don't you! You go first!"
"It was weird how Luna could instantly snap or bend, but hide it under her icy outside. It was... honestly... {b}kind of cute{/b}."
"You know, maybe I wouldn't mind being on this island with her. Maybe... if we somehow got off this place, we could stay in touch?"
"Maybe we could stay a while here too, it's nice and-"
a"Ow! What the fuck was that for?!"
l"C-Come on already! Are you going in or n-n-n-not?! Hurry up! Don't keep me waiting!"
a"Oh yeah, sorry, let's go."
l"Don't tell me what to do! Now go!"
a"Alright! Calm down! I was just kidding!"
l"You better be!"
l"Welcome to my room. It's also the only room in this whole cave, other than the bathroom."
"She walked over to the bed, took out a t-shirt and a pair of shorts, and began to-"
a"Woah, woah, woah! What are you doing?"
l"I'm getting ready to take a shower, didn't you forget? I said so earlier. Unless... you want to go together? Or maybe... take a peek? I have a pair of scissors you can use to cut a hole in the shower curtain."
"She winked at me, a twinkle in her eye. I felt a hot red spread all across my entire face. I probably looked like a tomato, or an apple."
a"I-I-I-I-"
"Too late, the image already made its way into my head."
a"I just came in to take a look, I don't w-w-want to-"
l"Just kidding!"
"She suddenly shot an icy glare at me, a complete change in mood."
l"You won't be leaving this room alive if I catch you anywhere near that curtain. I'll be caught dead before I get peeped on by a disgusting worm like you."
"I laughed nervously, the heat from my face still rising, like a kettle that began to boil. I felt my palms become clammy, and covered in sweat."
a"Ahahaha... of c-course. I won't be d-d-doing that..."
l"And don't touch anything either..."
l"Or. Else. You. Won't. Be. Seeing. Daylight. Ever. Again."
"I felt the air around me heat up, I struggled to breathe, and I felt myself be choked by some kind of invisible force. Was this the kind of pressure Luna had on people?"
a"Yeah... of course... take your time."
"She threw open the door, and strided in."
"Well... I guess I have to wait until she's done. What kind of person lets you into their house, and then immediately goes off doing her own thing?"
"She told me not to touch anything, but there's nothing against taking a look around, right? Let's see what we got here."
"Well... we have a small cot here, a small light hanging off the roof of a cave, a small desk... a trash can... and... oh? What's this?"
"Resting on top of the desk, illuminated by a small desk light, was an old photo, blurred by age, but clearly still recognizable."
a"Is that... Luna in the picture?"
"I tried to lean in to get a closer look, when suddenly-"
# Note: Luna is now wearing a t-shirt 
l"Hey! What the hell do you think you're doing over there? Are you trying to look for my underwear? Why you... by the time I'm done with you, this island's about to have a lot more room!"
a"Luna! Luna! Please, calm down! I can explain, I swear I'm not looking for your underwear!"
l"You have five seconds to start explaining before there's only one of us getting out of here alive."
a"Uh... I was just... looking at..."
l"Five..."
a"Woah, woah, woah! Give me a second!"
l"Four..."
a"I was looking at that picture on your desk! I swear! Please don't hurt me!"
l"Oh. I guess that's okay. What's wrong with the picture?"
a"Well, I was going to take a closer look, but... you know... you came out, talk about a quick shower."
l"I was just changing, and cleaned myself up a bit. What kind of person goes into a shower without a towel anyways?"
a"I... I guess that makes some sense. Uh... do you mind if I take a closer look at this picture?"
l"There's not a lot of stuff in here anyways, so go ahead. Just. Make. Sure. You. Don't. Touch. Anything. Else."
a"O-O-Of course, I wasn't going to!"
"Wait hold on, is this a picture of-"
l"Yeah, that's a picture of me, what's wrong?"
a"I thought you said you had no idea who you were!"
l"That's because... I don't. What are you blabbering on about anyways?"
a"Well... isn't this the beach?"
l"There's more than one beach on the planet, Atlas. Besides, I'm not lying. Why would I? If I lied, and you found out, how would that help either of us?"
a"That's... a fair point."
"It still kind of bothered me to see that picture. She looked a little bit younger in that picture, I'm guessing that was like... 3 years ago?"
a"Wait, you look kind of different in that picture. Like... a little bit younger."
l"Oh what, I'm not young enough? Yeah, it's a picture of younger me. And I'm not that old anyways! I'm twenty!"
a"I wasn't going to ask that! Stop assuming stuff! Wait... you're 20?"
l"Yeah, I'm twenty. How old are you, anyways?"
a"I uh... don't actually remember. I'm an amnesiac, remember?"
l"And... so am I."
a"Uh... I guess if I had to guess... I'm about... 21? I think?"
l"I don't remember asking."
a"You just did!"
l"Well, there you go. Proof I'm an amnesiac."
a"That's not proof that you have amnesia-"
l"I don't care. Anyways, your turn."
"I stared at her in confusion."
a"My turn for... what exactly?"
l"Why do I always have to spell everything out for you? Your house! I showed you mine, now let me see yours!"
a"But, you already know where it is!"
l"So? I let you into my house, now let me go into yours."
a"B-B-But-"
l"Unless... you have something... private in there?"
a"What?! Of course not!!!"
l"Then, I believe you'll be leading the way, Atlas."
a"Fine!"
"She stacked the exact same cards I used against her on me, and it worked out pretty good for her too."
"I didn't really have a choice but to let her go with me. She doesn't really like me as it is."
l"What are you waiting for? Let's go already."
a"Hmph."
"And so, with me leading the way, we made our way through the garden, and back to the town square where my house was."
a"You've already seen it, it's not like it's anything new to you."
a"Anyways, a deal's a deal. Go ahead, make yourself comfortable. It's not like there's anything important here, just my room."
l"Then... why are there two floors?"
a"You think I designed this house? I have no idea! The first floor is just an empty room with stairs up!"
l"Don't get aggressive with me. You think you're the one in charge, just because you're the one leading me for once?"
a"What?! No one's in charge, what are you saying?!"
l"Hm. You'll see it soon enough, just wait."
"With that, she made a sharp one-eighty, and walked through the front door like she owned the place."
"Jeez, she's so hard to deal with. Well, I better head in before Luna starts demanding I peel her a grape or something."
"I guess she went straight to the second floor, she's no where to be found in here."
a"What happened here?!"
"I stared in awe of the mess my room had become, drawers were flipped upside down, the closet was raided, all the clothes thrown onto the floor, crumpled and unfolded."
a"Luna! What the fuck did you do to my room?!"
"Wait, where was she?"
"I looked around the room, and despite the chaos, Luna was no where to be found anywhere."
l"I'm over here, look down."
"I looked down, and like a mole, Luna's head popped out between a table, a poster, and a pile of of sweatpants."
a"Why are you hiding under my clothes?! What the fuck did you do to my room?!"
l"For your information, I'm not \"hiding\", I'm investigating your room."
a"Well, you didn't have to tear it apart, even a tornado would be impressed! Why are you doing this?!"
"She stared at me blankly, before retreating her head back into the pile of furniture and clothes."
a"Oh no you don't! You come back here right now, and fix everything you just did!"
l"Mmph. Hmmprh rmm mrm."
a"Agh!"
"I reached my hand into the mess, and fished around, trying my best to look for Luna."
a"Aha! There you are!"
"Grabbing her hand, I pulled her out of the pile, and back up onto her feet."
l"..."
a"Now explain yourself! Why did you tear apart my room?"
l"Are you deaf? I told you already, I was investigating your room!"
a"Why?!"
l"...Congrats, you passed the test."
a"Test? What in the world are you talking about right now?"
l"I didn't know if I could trust you, so I tricked you into letting me into your room. It was all part of my plan."
"My mind flashed of bits and pieces of yesterday, as well as this morning. Did she really plan this all out?"
"The beach... the garden... her room... did she plan that all out so she could investigate me?"
"Was it all... a lie?"
a"So you're saying... that was all a lie?"
l"If you phrase it like that, it makes me sound like a villain. Believe me, I truly wanted to work with you. But unlike you..."
l"I'm not an idiot. I saw this chance to see who you really are, and what your connection is to me."
a"You could've at least been more careful with my room."
l"Well, it's been a nice day, but it looks like it's getting late. I think I'll go back to my room, and take that shower and nap I was talking about. See you tomorrow."
a"Don't think you're getting anywhere! You caused this mess, you fix it!"
l"I don't think I \"caused\" anything. Bye."
"She turned away to open the door and leave the room, but quickly, I grabbed her wrist before her hand touhed the doorknob."
a"Fix. Room. Now."
# Luna is sighing
l"Fine. But don't think I'm doing you any favors. You're helping too, or else you can work out this island by yourself."
a"You'd probably screw it up if I left you to do it by yourself anyways. C'mon, let's start with the bed, and then work our way towards the door."
l"Sounds good."
"And so, we spent the rest of the afternoon cleaning up the room. Piece by piece, we slowly began to bring the room back to how it started."
# Insert flashback graphics
a"I mean, surprisingly, it doesn't look like anythings broken, haha."
l"Shut up and help me move this desk back over to the wall. I can't move this thing on my own."
a"Oh, big whoop! I don't {b}have{/b} to do anything! I'm just doing this to make sure you don't screw everything up again."
l"Tch. Once I'm done with this desk, you better hang that mirror back, Atlas! You can't make a lady do all this work!"
a"Lady's a bit of a stretch. I don't know what you're talking about, anyways. I put that poster back up! I think I'm lucked out. A shower would be nice."
l"Why you..."
a"Wait, what are you doing with that window bar?! Put that down! Put that down!"
l"I'm sorry, I must be getting old with age, you have to tell me again. What was that?"
a"Okay! You win! I'll put the mirror back onto the bathroom door! Just please put that bar down! I'm begging you!"
l"Why, how nice of you to help me out Atlas! I appreciate it!"
a"..."
# sun is getting lower, room begins to tiden up
l"Atlas, where do I put all those sweatshirts?"
a"Didn't they fit into the closet?"
l"No, only the jeans and the t-shirts fit into there. There's no more room."
a"No more room? But if you folded them and laid them down there should be plenty of-"
a"Wait, hold on! You folded those first, right?"
l"Huh? I was supposed to fold them?"
a"You've gotta be kidding me-"
# throws open closet, EVERYTHING IS A MESS
a"How do you even live like this? This shouldn't be possible! Luna, why didn't you fold the clothes first?"
l"I... don't know how."
a"..."
a"You're kidding."
l"I'm not."
a"..."
l"Okay, I'm kidding, I just didn't want to fold it. Cut me a break here."
a"You could've just told me to do it!"
l"Yeah, but I don't wanna."
# start of sunset, room is almost done cleaning up with
a"Haha! Check this out, Luna! I can get stuff done too! Look how I put this window curtain back up!"
l"That doesn't look quite right. Why are the ends so long?"
a"Uhm, because it's supposed to cover the entire window, duh."
l"Why is the curtain wet?"
a"..."
a"That's not a window curtain, is it?"
l"No, it's a shower curtain. Are you {b}trying{/b} to keep me here, or are you just that stupid? Let me go home!"
a"I'm sorry! I'll fix it up right away!"
l"What are you apologizing for? It's {b}your{/b} room! I could care less if you put the shower curtains up! But guess what? {i}Someone's{/i} is keeping me here until we're done!"
a"Don't try to act like you're innocent! Did you forget who caused all this?"
l"Hmph."
# late sunset
a"Alright! I think that should be about it! Woohoo!"
l"Just let me go home already."
a"Sure, go ahead! Thanks for helping me reorganize the place-"
"I noticed a small slip of paper hanging out of Luna's side pocket. She looked like she was trying to hide it, her right arm hanging over it."
a"What's that in your pocket?"
l"Nothing. Why?"
a"It's just, I'm sure you didn't have that when you came in."
l"Well, mind your own business then!"
a"Really rich coming from the one that tore my house apart."
l"Whatever, is the interrogation over yet or not?"
a"Just let me see what you have!"
l"Fine, whatever, it's not like I care anyways. You can have it back."
"She took the paper out of her pocket, and handed it back to me, although somewhat begrudgingly."
a"What? What is this?"
"It wasn't a slip of paper, it was an old photo from an instant camera. I brought it up to my face, so I could get a better look."
a"This is-"
"It was a picture of me. But... who is this other guy?"
"He had blonde hair, a round face, dressed up in a flannel sweater and cargo pants. He looked to be about my age, and the two of us looked to be hanging out, or something."
"And where we were standing... it looked like, the shopping district? It was the same cafe as the one on the street Luna and I vistied this morning."
a"Luna, where did you find this? This is huge!"
l"It was in the pockets of one of your pants."
a"This is, this is crazy! I mean, this cafe, and this person, does this-"
"I started to ramble on and on, pretty much incoherently, my words becoming a blur of thoughts."
a"And then this outfit, it's-"
l"This is exactly why I tried to hide this from you. Shut up already. I can't understand a word you're saying, so I'll say it for you."
l"I'll be honest, I don't know who this guy is, but I doubt he's on the island."
a"But the cafe-"
l"It looks like some kind of chain cafe. They're probably everywhere, I doubt you'd think that you're in the same place just because the cafes the same chain."
a"Who is this guy though?"
l"I just said I don't know, pay attention next time. But there's no guarantee he's on the island with us."
a"But he's gotta have something to do with my lost memory! We can definitely find out if we look hard enough here! Maybe there's another photo somewhere around, the island, let's go!"
l"I'd rather not."
a"Why? This could lead to something big, maybe even you can find something if we look hard enough!"
l"Because look outside, you brainlet. It's dark out, and I was supposed to be home several hours ago."
l"I'm tired, and I don't feel like doing anything that's not going to bed."
a"Are you serious? You've got to be joking! You're gonna wait until tonorrow to check this out?"
l"Why would I be joking? Like I said, I'm tired. It's not like we have a time limit. Plus, I promised to show you the library tomorrow, right?"
# this be a flashback
a"Okay... maybe I did, uh... sorry for interupting you, carry... on?"
l"As I was saying, we'll come back here tomorrow, I'm done for today."
# end flashback
"Oh yeah, she did say something about that earlier, but I kind of forgot, well, other than her exploding."
l"So are you going to let me go home or what? Because if I'm tired tomorrow, nothing's getting done."
a"Wait, hold on. Let me take you."
l"Do you have to follow me everywhere I go? You're so annoying, ugh."
l"Fine, if you don't keep me any longer, I don't care."
"With me leading, the two of us headed down the stairs, and out the front door."
l"I'm sure you didn't forget where I live, right?"
a"Of course I do! It's on the beach, under that cliff!"
l"Good, you remembered, we can actually cut through this way and skip the garden, it's faster."
"She pointed to the road that was on the left hand side of the route I usually took."
a"The garden just cuts through that road anyways, right?"
l"Yeah, that's right. So are we going or not?"
a"Jeez, don't be so uptight!"
l"..."
l"No."
a"What? Why not?"
l"It's just, I don't feel like talking about it now. Let's just go."
a"If you insist, sure."
"\"No?\" Why would she openly reject that?"
# back at the beach, late sunset becomes night
a"Well, this is the shore, but your house is on the other side of the island, right?"
"She nodded, somewhat distracted. She was staring off into the ocean again, just like yesterday."
a"Didn't you want to go back already?"
l"No. Let me stay for a bit, you can go back. Thanks, I guess."
"Curious about what she was staring at, I also stared off into the ocean, the moonlight reflecting off the horizon."
a"The moon... doesn't it look like it's waning?"
l"Atlas, let me ask you a question."
a"Sure. What is it?"
l"If... we were stuck here, without our memories forever, what would you do?"
a"Well... with you here, it might be a pain. That's for sure."
l"I'm not kidding. What if we couldn't get anyone to rescue us?"
a"I don't really know, I can't see the future, or anything like that. I'd probably just live out the rest of my life, and figure out stuff as it goes."
a"Maybe, I'll... like write a book or something like that, y'know? Maybe if I'm dead, someone will find me, and read it."
l"Hm. Now... what if I wasn't here either?"
"I never really thought about that. Being stuck with Luna was one thing, but being by myself was another."
"I felt the air around me tightening up, the air in my lungs becoming heavy. I was struggling to breathe."
"It might've been the question, but I, in all honesty, had no idea how to answer her."
"So, I just told her:"
a"I... don't know. Certainly it wouldn't turn out like this, that's for sure. What about you?"
a"What if \"you\" were stuck here forever, and alone?"
l"Hm. Probably the same as you, but let me just say. I won't die without my memories."
l"Atlas, you ever heard of reincarnation?"
a"That's like... when you become someone new when you die, right?"
l"Wow, you should deserve a gold star! Just two more and you get a free pencil!"
a"Were you going to say something or are you just going to make fun of me?"
l"Right, well, do you think memories are stored in some kind of bank?"
a"A bank? Like... at the back of your mind?"
l"No, it's more like, a cloud save. You know what that is, right?"
a"Of course I do! Do you take me for some kind of caveman?"
l"Well, what if we actually \"did\" have our memories? It's just... we're locked off from them?"
a"Wait but, the brain stores all the memories!"
l"You know how a computer and a monitor works, right?"
a"The monitor picks up whatever the computer sends as information, and then displays it. Easy."
l"So... what if our brains were the monitors, and there was some invisible force that connected us to the monitor?"
l"The reason we don't have our memories is because someone frayed the cable that connects the two."
a"That means, whoever trapped us here, must have frayed that wire!"
l"Good job. One more gold star left!"
a"Oh, bite me. What does that have to do with us right now?"
l"Nothing, really. It was just at the back of my mind."
a"Then why would you say it?!"
l"Because I know you're too dumb to understand what I just said."
a"Huh?"
l"Nothing."
l"Anyways, I'm gonna go back now. You don't have to come. Are you still gonna stick around tomorrow?"
"I don't know what kind of answer she was expecting, but it was pretty obvious what I was gonna say."
a"Well, obviously. You promised to show me the library, and you'd better!"
l"Yup, I did. See you tomorrow, and you better not be late this time."
a"Y-Yeah, I won't. I'll be there early."
l"Good. Sayonara."
"Abruptly, she turned and walked away, her footprints leaving small marks in the sand. With every passing wave, more and more of the footprints were covered."
"Once again, the beach turned pristine again, just like yesterday, like today never happened."
"The only difference was the moon, which had become ever so slightly thinner, slowly waning."
"In the moonlight, I took out the photo Luna had found in my room, and took it out if my back pocket."
a"This guy... why does he look so familiar, and why isn't he here with me?"
a"Maybe... he's someone that I knew before I ended up here. Actually... definitely."
a"Luna might've just dismissed it, but I'm sure this coffee shop couldn't have just been a coincidence."
a"Lastly... whoever took this picture of us must also have some sort of connection! It has to mean something, about why they put it into my room!"
"I would've liked to look around the island for more clues, but it was too dark, and honestly I was pretty tired."
"Between walking around the island, and also having to clean up after Luna, a nap right now would be superb."
"So, obviously coming back tomorrow would be the smart idea. I headed back around the shore to my house."
a"I guess I'll turn in for tonight, it's not like there's anything left to do anyways."
a"Still though, that picture's still kinda weird, isn't it?"
a"That guy..."
"Who is he...?"
"Why was Luna so mad about the library too?"
"And why was she so suspicious, flipping through my room like some kind of tornado."
"Wait, could it be...? Are those three connected somehow?"
"Maybe she knew that guy, or maybe something else like that."
a"Oh, to hell with it! I'm tired, and I'm going to bed, I'll deal with this crap tomorrow!"
"I threw myself onto the bed, and closed my eyes, as the moonlight shined through the windows."
"I didn't bother to even try to close the window curtains. I was just that tired."
a"Hah..."
#bitchboy goes to sleep
"I woke up to a shade of orange, the same kind you'd get from a fireplace."
"Oh... good morning, I guess."
a"Damn, it's pretty early out here. I don't even think the sun's even out yet."
"And I was right. The windows still had an orange tint, the morning sun starting to rise."
"I probably wasn't going to go back to bed, so I just decided to get up at that point."
"I got out of bed, and walked to the closet, choosing an outift to wear for the day."
a"Well uh... let's see. A hoodie seems like a good idea."
"As I walked over to the bathroom, and began to brush my teeth, a thought came into my head."
a"That's weird... that weird green lady... how come I didn't dream about her last night?"
a"In fact, I don't even think I dreamed yesterday anyways. Wow that's kinda weird. Maybe it {b}was{/b} just some kind of weird dream."
"I finished up brushing my teeth, and went back to my bed to look at the window."
"The sun wasn't fully out, but I'm pretty sure it was a good idea to head out early. After all, yesterday she was waiting for me all morning."
a"Oh shoot, I almost forgot."
"I took the photo Luna found yesterday from my desk, and stuffed it into my back pocket."
a"Alright, looks like I got everything. Let's head out, Atlas!"
"As I walked onto the beach, I spotted a familiar silhouette in the dim sunlight."
a"No way. You've gotta be kidding me."
"I walked closer to get a better look, my feet leaving deep and wet footprints in the beach sand as I started to run towards the silhouette."
"It looks like I was right. It was Luna, and it looks like she noticed me too."
a"Luna? What are you doing out here so early?"
l"Oh... it's you."
a"Jeez, you look terrible, what happened yesterday?"
l"Mind your own business..."
"Even when tired, she snapped back at me just as sharply as she normally would have."
l"I guess... I'll tell you. I didn't get a single wink in last night. But even then... it looks like you slept like a rock, so at least one of us is happy."
l"I came out for a walk at about midnight, and I've been here for the whole night."
a"Well, it looks to me that you need to rest! You look like you're gonna faint."
l"I'm fine, idiot. Here, let me show you what I've been looking at. See the horizon? Look."
"The morning sun was starting to rise, and its reflection bounced off the surface of the water. Though it was bright, it wasn't quite enough to make you squint."
a"Uhh, what's so special about it? It's just the sun on the horizon."
l"You're hopeless. Look at it. Doesn't the surface of the water remind you of anything?"
a"It's just water, right?"
l"The water's just like that mirror in your room, it reflects anything. So then, do you think there's another world under that reflection?"
a"It's just the light bouncing off the surface. C'mon, you know that too, stop kidding around."
l"Well, what if to that world, we're just light bouncing off their surface too? How would you know which one's just light?"
a"I... never thought about it like that. That's uh..."
l"And... maybe these \"other versions\" of us had our memories?"
a"Then why would they do the same things as us? Wouldn't they be acting differently to us?"
l"That's because you think they're the reflections. What if we were the reflections? We wouldn't have to think, after all, we're just copying them."
"That was honestly a pretty scary thought. We weren't really us? Is that kind of thing even possible?"
l"Looks like it got to you. Creepy isn't it, thinking that neither of us are really here."
a"Yeah, you're right. I can't imagine anything like that."
l"Well, in that case."
l"You should be glad that I was kidding."
a"W-W-What?"
l"I said I was joking. Stop making me repeat myself, I'm sick of it."
a"Then why would you say something so weird? I actually believed you!"
l"So you can learn your place, court fool. A little shock's bound to keep the dog in the fence."
a"Stop calling me a court fool!"
l"Stop following me, then."
a"..."
l"That's exactly what I thought. Anyways, look up, the sun's pretty much out."
"I looked back over to the horizon. She was right, the sun was pretty much out, the orange shade of the sunrise slowly began to give way to an bright blue shining off the water."
l"Do you think the sun can wane like the moon?"
a"This is another weird existential joke isn't it? Let me guess, what if we were star aliens from another universe, and the sun banished us here because we were on Santa's naughty list?"
l"How did... how did you know?"
a"Huh? I was right?"
l"Of course not!"
"I felt a hot searing pain across my cheek as her hand made contact with my face."
a"Ow! What was that for?"
l"For speaking out of order. As I was saying, why do you think the sun doesn't wane?"
a"Because the earth can't cast shadows on the sun, duh. The moon's reflecting light from the sun, and the Earth is just blocking it."
l"That's certainly the most objective way of looking at it, but... what if-"
a"Stop! Please! I can't take it anymore!"
l"Well, I guess I've gone a little bit overboard for today."
a"Of course you have, and you know it!"
"She smirked lightly at the comment, fully conscious of her actions."
l"Well, it's always better to have more than less."
a"Uh so... you still look kinda tired, do you wanna like... call it off for now or what?"
l"I'm fine. Mind your own business, I'm going to go freshen up a bit."
l"And remember... don't you dare. Come. In."
a"I got it, I got it! You don't have to remind me!"
l"Good, the court jester hath yet but yield to thine awe."
a"...What?"
l"In your caveman terms, it means... how should I phrase this? \"You're my bitch\"."
a"Huh?"
l"Bye, see you at the library."
"She walked off with the same sarcastic energy as always, but it looked a little more like a limp, seeing how she hadn't slept."
a"Oh come on!"
"Deciding there was nothing else to do at the moment, I took out the photo from yesterday, in my back pocket."
"Maybe it all connected to Luna, maybe it all took place on this island. It would explain everything, but that would mean... {b}she's lying{/b}."
"Still though, what kind of role do I play into this? Is there something about my memory that's so important?"
"And this guy... the guy in the photo, maybe... he's hiding somewhere on this island. Why? I still have no idea."
"At the end of the day though..."
a"*sighs* I really can't be sure, without any evidence. It's not like this photo's gonna give me all the answers."
"I guess I better get going. I'm pretty sure Luna wouldn't like it if I were still here by the time she got out. She'd probably think that I'm some kind of creeper or perv."
"As I passed by the garden, I noticed what looked like a small slip of paper on the field of grass by the flower ring."
a"What the hell?"
"I stopped to take a look, to find that it wasn't a piece of paper at all. It was a photo. I picked it up, and put it up to the sun to get a better look."
"This was... the same photo of Luna that was in her room yesterday. So... why was it in the garden of all places? Luna didn't come to the garden, right?"
"The frame was blocking it, but by itself, it was pretty clear that this was from some kind of instant camera. Just like the one I had."
"I took out the photo from my back pocket, and compared the two in the sunlight."
"Luna said yesterday that it was all a huge coincidence, but it still threw me off that both of them looked like they were taken on the island."
"The beach for Luna's photo, and the shopping district for mine, could it really be a coincidence? It didn't seem that likely."
"Well, I'm pretty sure that Luna wouldn't be too happy if she found out that I lost her photo, so I decided to just set the topic aside and shoved both of the photos into my back pocket."
"The library should be this way, through the forest."
"How did Luna even get here? This \"road\" is just a bunch of sticks on the ground. If someone messed them up, you'd easily get lost."
a"Gahh!"
"It was a sharp branch overhead. It hit me, and some of it got stuck on my shirt too."
a"Come off, you good for nothing weed!"
"It was no use, the more I pulled, the more of them got stuck on me. There were thorns all over my pants too. Every inch of my body was covered in sharp plant growth."
a"Argh!!! I hate this crap!"
"I struggled and struggled, but still got tangled. Somehow, I managed to lift myself off the ground, and was being suspended off a branch by my shirt."
a"This is seriously the worst, man..."
"I was stuck completely, I couldn't even move my limbs without getting stabbed by something."
a"I... oh come on! You've gotta be kidding me! Screw this forest!"
a"Ugh, looks like I don't have any other option. I gotta untangle myself from this thing."
"I started to unhook myself from the thorns. First, I freed my pants, and I was able to move my legs."
a"Alright Atlas, you can totally do this, easy with the shirt... and..."
"The moment I unhooked my shirt, I felt myself fall from the tree, with a loud crash."
"The pain was sharp, and instant. I felt myself black out, and I fell unconscious."
"By the time I had woken up, I found myself surrounded by leaves, and tiny branches."
a"Ow... where the hell am I?"
l"Wake up, idiot."
a"Wha? Luna? When did you end up here?"
l"I heard that crash from the beach. How did you get stuck in a tree, and then fall into a bush? I didn't know you were a clown of physical comedy too, though those clothes might say something else."
a"Woah, hey! I like this shirt! And are you only here to make fun of me, or are you going to help me out of here?"
l"If I'm gonna help you, you're gonna have to clean yourself up. If you get blood everywhere, who knows, I might catch your diseases."
a"For your information, I'm clean! What kind of diseases could I even give you?"
l"Stupidity."
a"Just help me put of here already! I think there's a thorn in my face!"
l"Shut up, I'm on it. Hold still."
"She yanked me by foot and I came crashing through the bush, landing on my butt. The rough forest floor definitely didn't help."
a"Ow, ow, ow! Couldn't you have been a little more gentle with that?"
"She rolled her eyes, and completely ignored me, instead pulling out a small pocket mirror from her pocket, and showed it to me."
l"Look at yourself, you look like a complete trainwreck, and I didn't even know it was possible to look than worse than you normally do, but you proved me wrong."
a"Whatever, I'm fine."
l"I'm not going anywhere with you looking like that. Go clean yourself up. Now."
a"Ah jeez, you're really a pain, y'know?"
l"Takes one to know one. Hurry up, let's go."
a"Well what am I supposed to do? I don't have a towel or anything on me!"
l"Go find a towel and some water, obviously. Are you really that stupid?"
a"I don't wanna walk all the way back to my room, that's gonna take forever!"
l"Well, you go figure it out, I'm going to go to the library, hurry up."
"She took the mirror back, and put it into her pocket, before turning back to me one last time."
l"Ciao."
a"Wait, hold on!"
"It was too late, she was already out of eyesight. Surprising how fast she could walk."
a"Aw..."
"Feeling that I didn't have any other choice, I headed back to my room to clean myself off."
a"Stupid plant... I hate trees..."
"Still covered in blood and thorns, I stumbled over to the mirror."
a"Oh wow, damn."
"I was bleeding from almost every part of my body, from head to toe, pretty much everything was covered in thorns."
"Painfully, I slowly plucked every single one out, each one hurting more than the last. It was sharp, and instant."
a"Gahhhh!!!"
"And that was the last one. The blood seems to have cleared off of the wounds, but I was still covered in dried blood."
a"Man, this really sucks. At least it doesn't really hurt, I guess."
"I stepped into the shower and rinsed myself off, until all the blood was washed off. Now fully cleaned, I came out and put my clothes back on."
"They were still sort of torn up, but it wasn't anything serious. I left the house, and went back to the forest to the library."
a"Alright man, careful this time. Don't cut yourself, and don't get stuck."
"Slowly, I took a small step after another, making sure I didn't stray too far off the path."
a"Come on, just through a little bit..."
"Bingo."
a"Woohoo! I'm here! Yo, whaddup!!!"
l"What are you talking about, idiot? Shut up, this is a library."
a"Oh... hey Luna. Uh... sorry for the wait, but uh... I'm here."
l"I can see that. I can also see those rags you call clothes. Didn't you change?"
a"Oh c'mon! It's just a few scratches!"
"Luna, hands behind her back, walked around, slowly inspecting me like some kind of drill sergeant."
l"So... it would seem like you didn't realize that half your back is all exposed."
a"More manliness to show, obviously!"
l"You're not funny, Atlas."
a"Oh, give me some credit for trying!
l"..."
"For a second, I thought I saw what looked like a small blush coming from her, but as she caught me looking at her.."
"She instantly toughened up into her usual annoyed face."
"The library's outside was huge, it looked more like some kind of cathedral than a library."
l"Shut up, let's go into the library."
a"Alright... whatever you say!"
l"Here. The library. Behold."
a"Why were you so uptight about this place yesterday?"
l"Because I didn't want to."
a"You're... kidding, right?"
l"Not at all, I was just fed up with you, so I didn't want to show you the library."
a"Uh..."
l"Of course I had a reason! Shut up, court fool."
"The level of the library we were on looked like an actual library, with TVs everywhere, and modernized furniture."
"It was a complete contrast the outside of the library, which looked medieval and like a monument."
"While it was weird, I still didn't see why Luna wouldn't let me in here."
l"I know what you're thinking, Atlas. \"The first floor looks completely normal, so what's the big deal?\""
a"I mean, of course that's what I'm thinking! There's nothing wrong with the library."
l"That's what you might think, and you're partially right. But you forgot, a building as large as this one..."
a"Has a second floor?"
l"Exactly. And there's not quite much up there either... except for this."
l"It's up the stairs, don't hit your head, or else you'll lose what little brain matter is up there."
a"I'm perfectly able to walk up a staircase, thank you very much-"
l"Then prove it."
"She shoved me aside and made a beeline for the staircase, which was made out of marble in a spiral design."
"Once she was at the top, she called out at me:"
l"What's taking you so long, let's go, court fool! Your master's waiting for you!"
a"Why you-"
"Slightly pissed off, I ran up the stairs, straight towards Luna, until-"
a"Ow!"
l"Pff!"
"She couldn't control herself. I hit my head on the low hanging ceiling, which I didn't notice was getting closer as I ran up the stairs."
"Even so, it was new to see Luna laughing, even though she clearly was laughing at me."
l"Hahahaha! What did I say? You idiot!"
a"Grr..."
l"If you hate it, you don't have to stay, you can go back down the stairs. Watch your head though!"
a"Alright, we get it! I hit my head, what did you want to show me?"
l"Wait, wait, wait! Look at yourself! Ahahaha!"
"Giggling uncontrollably, she pulled out her pocket mirror and showed me."
"Aside from my cuts I got this morning, I noticed the large bump on top of my head."
"It was practically the size of a kid's hand, and... it wouldn't stop swelling."
"Luna put the mirror back, and kept on giggling the whole time, her face turning red."
l"Oh, you look so dumb!"
"In a final attempt to keep myself from being the butt of the joke, I remembered the photo I found this morning."
"I took it out from my pocket, anthd put it right in front of Luna's face."
a"Oh, so I guess you don't want {b}this{/b}?"
l"Hah! Wait. Is that-"
"It worked, she returned back to her grumpy self, which, I hope I'll never say again, I preferred."
l"Why do you have that, you disgusting perv! Was it when I was in the shower, you creep?!"
a"Stop calling me a perv, I found it when I was walking through the garden to the forest. Why did you even take it out of the frame?"
l"Why should I tell you, thief? It's not yours, is it?"
a"Alright, fine, here you go."
"I handed her the photo, which she took without any hesitation."
l"I brought you here, in case you were wondering, to take a look at this."
"She walked through the hall of the second floor, which although was a lot less filled with books, resembled the medieval look of the outside more."
l"You. Look at this."
"She was pointing to a pedestal hidden behind two bookshelves, almost like it was never meant to be found."
a"What about it? It's just a pedestal."
l"No, read what's on it."
a"Uh... let me take a look."
"I took the book off the pedestal, and quickly flipped through the pages, when I realised:"
a"Hey, wait a second, these pages are all blank!"
l"You're such a simple-minded person. I bet even breathing's a task for you. Look at the first page, there's something weird written on it."
"I flipped back through the pages, and indeed, she was correct. On the first page, there was a small paragraph. I bent down, and took a closer look."
a"Uh... here goes nothing."
a"\"Truth had left the realm of earth, and the Sky had left the realm of the Sea.\""
a"\"Long ago, these two had lived in harmony, within the petals of a flower.\""
a"\"One posessed the heart of blue, and one had a soul of earth, the two had yet to 
a"\"As the flower grew and grew, an infestation of locusts appeared.\"
a"\"Truth had gone, and no titan could hold back the sky.\""
a"That's it. Luna, do you have any idea what this means?"
l"I don't. I found it two days ago, before I unfortunately met you, as I was looking around the island."
l"Your guess is as good as mine, so... have at it."
a"Wait a second, there's something written on the pedestal."
l"Whatever. Just don't get your head stuck in there or something."
"Ignoring her, I bent down, and noticed that, on the side facig towards me, there was a small engraving in the wood."
a"It says... \"Property of the city of Ren Harbor\"-"
"Suddenly, I felt a sharp pain in my head, my whole body began to shake, and it felt like there were a thousand knives cutting through every inch of my skull."
a"L-L-Luna!"
"In the pain, I glanced back at Luna, who was also experiencing the same pain, her hands around her ears, the slightest sound causing her immense pain."
l"What did you do?!"
a"I-I-I don't know!"
"I found myself losing balance. I hit the pedestal and it came crashing down, a loud reverb across the whole room amplified by the size of the hall."
"The sound was terrifyingly painful, like a bullet through my skull. I writhed in pain, and felt myself drop to the ground."
"My vision began to blur, and the whole hall began to twist and deform. The only shape I could stil make out was Luna, who was also on the ground, screaming in pain."
l"What's happening to me?!"
"More and more did the world around me begin to twist, until even Luna was blurred into just a mess of color and shapes, just as unidentifiable as everything else."
"Everything was a mess. Even the sounds I heard sounded alien, like I've never heard them before, all while still burning through my head, searing through my whole body as it shook."
a"Gahhhhh!"
"At last, the pain was too much to bear, and I felt myself losing hold on reality, as I slipped into darkness."
