# NOTES FOR YOU PEOPLE:
# a = Atlas (for when he speaks directly)
# g = Game (a message from the game directly to the player)
# l = Luna (for when Luna speaks directly)
# q = ??? (for when an unknown speaker speaks)
# No letter assigned: (internal dialogue, like thinking, or narration)
# In addition, before Atlas gains his name, he will speak in \"*insert text here\"

# DAY ONE

"The soft sound of ocean waves hitting the soft shore was the first thing I remembered."
"The next thing I remembered was the soft, warm, and bright rays of sunshine on my face, waking me from my gentle sleep."
"That's about all I could remember. Besides that, my mind was clear, I couldn't recall my age, name, or anything like that."
"\"Where am I? What is this place?\""
"My eyes slowly opened and greeted the bedroom I was in."
"\"Oh, this is…\""
"Not a place I was familiar with."
"Everything here was foreign to me... but I was overcome with a strange feeling of Deja Vu, like I've been here before."
"\"Who am I? Why can't I remember a single thing? Where is this place?\""
"I pointed at the window in front of me."
"\"Well, clearly that's a window, and those are curtains over the edges.\""
"Next, I pointed at the wall."
"That's a poster for some kind of rock band."
"How come I knew what everything in this room was, yet nothing about myself?"
"I know what these things are, but I still can't remember where they come from..."
"I couldn't put this feeling into words. It was like when you got lost in the woods, where you knew that there were trees everywhere, but you still couldn't figure your way out."
"I didn't even know what I looked like. Maybe I had dark hair, maybe it was light."
"Maybe that was a bit of an exaggeration, maybe I was just a bit in shock."
"I focused as hard as I could, trying to muster up a single ounce of knowledge about myself."
"..."
"Nope, nothing."
"Well, I guess I can at least figure out my hair color."
"I pulled down my hair, which although was short, was long enough for me to look at."
"..."
"Well, turns out I have brown hair. Guess that's at least a place to start."
"I glanced across from my bed, and noticed a mirror hanging on the wall next to the closet."
"Curious to see what I looked like, I slowly lifted myself out of bed, my muscles stiff like I just woke up from a deep sleep."
"..."
"Well, I guess this is what I look like."
"I was greeted by emerald eyes, dark skin, and brown hair. I don't really know what I expected, but it sort of surprised me to see how plain I looked."
"I just looked like any average guy that you might run into on the street."
"I felt like an outsider looking through someone else's eyes through this mirror, like this body wasn't mine."
"I mean, clearly, this was my face. After all, I'm looking at it, aren't I?"
"Still, I felt like a stranger, as I had no idea who this person I was looking at was. Was he a nice guy? Or was he a criminal?"
"Thinking about who I truly was made me a bit light-headed and dizzy, so I decided to stop. Instead, I tried to think about where I was."
"\"What's outside the bedroom? Where am I?\""
"I asked the question out loud, like I was waiting for someone to answer me."
"..."
"There was no answer."
"All there came was the sound of the ocean waves gently pulling and pushing, gently echoing against the walls of my room."
"Well, I can at least say, I am as clueless about this place as I was about myself."
"It's almost like I was a character from a video game, TV show, or something like that."
"In fact, it's script perfect actually."
"Step one: wake up in a foreign land. Check."
"Step two: have amnesia. Check."
"Step three: get magic powers, and find a hot girl. Uh... not check."
"Well, I suppose it's not {b}quite{/b} script perfect. But at least most of the steps are complete. After all, Rome wasn't built in a day."
"Still, I felt more like an NPC, or a side character at the moment, rather than being the charming and daring protagonist."
"But if I really was a side character..."
"Where is everyone else? Maybe someone here knows about me, and could lend me a hand or two."
"You know... this place is starting to have a musty smell to it. It's getting hard to breathe, I don't want to stick around for long."
"Some fresh air would be nice, and if I'm gonna try to find anyone, they're probably not gonna show up in my bedroom."
"I stretched out a bit, feeling my muscles relax from the stiffness I had earlier. After that, I walked out the door at the corner of the room, and found myself in what looked like a town square."
"The soft sounds of the ocean waves hitting the shore I heard in the room became clearer, like a pair of misty glasses getting wiped."
"The gentle sound of the waves and the gentle wind blowing onto my face was certainly relaxing, but I still felt just as confused as I was before."
"I took a few glances around the town square. The town square was empty, not a single person was in sight."
"The sounds of the ocean and the wind became hollow, as if there was something missing. The comfort I once felt with them became a deathly silence, trying to pull me into an abyss."
"I called out into the town square, becoming desperate for any response."
"\"Hello?\""
"..."
"Once again, I was only answered by more silence."
"The road itself wasn't very fancy, it would just have been like any old street you'd see on the street."
"Still, with no one here... it raises a pretty big red flag."
"If no one was here, who was keeping it in this good condition?"
"Puzzled, I went to look for more answers, moving on further away from the town square, to a nearby spot of greenery west of the square."
"The mere sight of the garden was a marvel in itself. It was beautifully grown, a ring of blooming roses and daisies surrounded a tall oak tree, and an adorned gazebo lay at the middle of the garden."
"Still curious to find anyone, I walked closer to the gazebo, taking a closer look at it. It was clean, but upon closer look..."
"There was a thin layer of dust on the floor of the gazebo, almost like the first flakes of snow on a cold winter morning."
"Chances are, no one's been here either, since this dust hasn't been disturbed in a while."
"*sighs*"
"\"What kind of place is this?\""
"\"I just want to find someone, anyone!\""
"\"Not only is there no one here, I'm lost as all fuck!\""
"\"Who the hell am I?!\""
"I shouted that question to the skies, who just as before, answered me with apathy."
"Frustrated, I headed back to the town square, tired and confused by the situation I was in."
"Maybe I took a wrong turn, but it wasn't the town square that I ended up."
"Am I... at a beach...?"
"Is this town... on the coast? Or maybe... it was an island?"
"I looked around me, and the beach stretched far beyond what I could see, like the horizon."
"I gazed upon the waters, to see if there was any kind of land I could spot."
"All that greeted me was the line that the sky touched the water, no land in sight."
"Still confused by how I ended up on the shore instead of the town square, I was about to turn back so I could head to back, until I saw what appeared to be a silhouette of someone on the sand."
"There appears to be someone here."
"A girl, I think. Noticing me, she turned towards me and stared at me."
q"..."
"I couldn't tell her age."
"She could've been anywhere from 14 to 25."
"She had a look of both maturity and youth to herself."
"\"Hey um... so...\""
q"..."
"Thinking that maybe she hadn't heard me, I tried asking again."
"\"Hey, it's nice to meet you-\""
q"Shut up."
"\"W-W-What..?\""
q"If I didn't answer you the first time, what made you think I'd answer you the second time? Have you got a single brain cell up there?"
"She sighed."
q"It doesn't matter."
"She turned and walked off, her footprints slowly being wiped away by the waves."
"As she took a few steps, she turned around towards me."
q"You. Come. Don't make me repeat myself, alright?"
"Honestly, she sort of bugged me and came off as bratty, but she's probably the best chance I have of learning what was going on with the town."
"I followed her as she walked on the shoreline, just far enough from the waves to stay dry."
"The tension in the air felt so tight I felt as if I could choke on it. Trying to break the tension, I tried to make small talk with her."

