# NOTES FOR YOU PEOPLE:
# a = Atlas (for when he speaks directly)
# g = Game (a message from the game directly to the player)
# l = Luna (for when Luna speaks directly)
# q = ??? (for when an unknown speaker speaks)
# No letter assigned: (internal dialogue, like thinking, or narration)
# In addition, before Atlas gains his name, he will speak in \"*insert text here\"

# DAY ONE

"The soft sound of ocean waves hitting the soft shore was the first thing I remembered."
"The next thing I remembered was the soft, warm, and bright rays of sunshine on my face, waking me from my gentle sleep."
"That's about all I could remember. Besides that, my mind was clear, I couldn't recall my age, name, or anything like that."
"\"Where am I? What is this place?\""
"My eyes slowly opened and greeted the bedroom I was in."
"\"Oh, this is…\""
"Not a place I was familiar with."
"Everything here was foreign to me... but I was overcome with a strange feeling of Deja Vu, like I've been here before."
"\"Who am I? Why can't I remember a single thing? Where is this place?\""
"I pointed at the window in front of me."
"\"Well, clearly that's a window, and those are curtains over the edges.\""
"Next, I pointed at the wall."
"That's a poster for some kind of rock band."
"How come I knew what everything in this room was, yet nothing about myself?"
"I know what these things are, but I still can't remember where they come from..."
"I couldn't put this feeling into words. It was like when you got lost in the woods, where you knew that there were trees everywhere, but you still couldn't figure your way out."
"I didn't even know what I looked like. Maybe I had dark hair, maybe it was light."
"Maybe that was a bit of an exaggeration, maybe I was just a bit in shock."
"I focused as hard as I could, trying to muster up a single ounce of knowledge about myself."
"..."
"Nope, nothing."
"Well, I guess I can at least figure out my hair color."
"I pulled down my hair, which although was short, was long enough for me to look at."
"..."
"Well, turns out I have brown hair. Guess that's at least a place to start."
"I glanced across from my bed, and noticed a mirror hanging on the wall next to the closet."
"Curious to see what I looked like, I slowly lifted myself out of bed, my muscles stiff like I just woke up from a deep sleep."
"..."
"Well, I guess this is what I look like."
"I was greeted by emerald eyes, dark skin, and brown hair. I don't really know what I expected, but it sort of surprised me to see how plain I looked."
"I just looked like any average guy that you might run into on the street."
"I felt like an outsider looking through someone else's eyes through this mirror, like this body wasn't mine."
"I mean, clearly, this was my face. After all, I'm looking at it, aren't I?"
"Still, I felt like a stranger, as I had no idea who this person I was looking at was. Was he a nice guy? Or was he a criminal?"
"Thinking about who I truly was made me a bit light-headed and dizzy, so I decided to stop. Instead, I tried to think about where I was."
"\"What's outside the bedroom? Where am I?\""
"I asked the question out loud, like I was waiting for someone to answer me."
"..."
"There was no answer."
"All there came was the sound of the ocean waves gently pulling and pushing, gently echoing against the walls of my room."
"Well, I can at least say, I am as clueless about this place as I was about myself."
"It's almost like I was a character from a video game, TV show, or something like that."
"In fact, it's script perfect actually."
"Step one: wake up in a foreign land. Check."
"Step two: have amnesia. Check."
"Step three: get magic powers, and find a hot girl. Uh... not check."
"Well, I suppose it's not {b}quite{/b} script perfect. But at least most of the steps are complete. After all, Rome wasn't built in a day."
"Still, I felt more like an NPC, or a side character at the moment, rather than being the charming and daring protagonist."
"But if I really was a side character..."
"Where is everyone else? Maybe someone here knows about me, and could lend me a hand or two."
"You know... this place is starting to have a musty smell to it. It's getting hard to breathe, I don't want to stick around for long."
"Some fresh air would be nice, and if I'm gonna try to find anyone, they're probably not gonna show up in my bedroom."
"I stretched out a bit, feeling my muscles relax from the stiffness I had earlier. After that, I walked out the door at the corner of the room, and found myself in what looked like a town square."
"The soft sounds of the ocean waves hitting the shore I heard in the room became clearer, like a pair of misty glasses getting wiped."
"The gentle sound of the waves and the gentle wind blowing onto my face was certainly relaxing, but I still felt just as confused as I was before."
"I took a few glances around the town square. The town square was empty, not a single person was in sight."
"The sounds of the ocean and the wind became hollow, as if there was something missing. The comfort I once felt with them became a deathly silence, trying to pull me into an abyss."
"I called out into the town square, becoming desperate for any response."
"\"Hello?\""
"..."
"Once again, I was only answered by more silence."
"The road itself wasn't very fancy, it would just have been like any old street you'd see on the street."
"Still, with no one here... it raises a pretty big red flag."
"If no one was here, who was keeping it in this good condition?"
"Puzzled, I went to look for more answers, moving on further away from the town square, to a nearby spot of greenery west of the square."
"The mere sight of the garden was a marvel in itself. It was beautifully grown, a ring of blooming roses and daisies surrounded a tall oak tree, and an adorned gazebo lay at the middle of the garden."
"Still curious to find anyone, I walked closer to the gazebo, taking a closer look at it. It was clean, but upon closer look..."
"There was a thin layer of dust on the floor of the gazebo, almost like the first flakes of snow on a cold winter morning."
"Chances are, no one's been here either, since this dust hasn't been disturbed in a while."
"*sighs*"
"\"What kind of place is this?\""
"\"I just want to find someone, anyone!\""
"\"Not only is there no one here, I'm lost as all fuck!\""
"\"Who the hell am I?!\""
"I shouted that question to the skies, who just as before, answered me with apathy."
"Frustrated, I headed back to the town square, tired and confused by the situation I was in."
"Maybe I took a wrong turn, but it wasn't the town square that I ended up."
"Am I... at a beach...?"
"Is this town... on the coast? Or maybe... it was an island?"
"I looked around me, and the beach stretched far beyond what I could see, like the horizon."
"I gazed upon the waters, to see if there was any kind of land I could spot."
"All that greeted me was the line that the sky touched the water, no land in sight."
"Still confused by how I ended up on the shore instead of the town square, I was about to turn back so I could head to back, until I saw what appeared to be a silhouette of someone on the sand."
"There appears to be someone here."
"A girl, I think. Noticing me, she turned towards me and stared at me."
q"..."
"I couldn't tell her age."
"She could've been anywhere from 14 to 25."
"She had a look of both maturity and youth to herself."
"\"Hey um... so...\""
q"..."
"Thinking that maybe she hadn't heard me, I tried asking again."
"\"Hey, it's nice to meet you-\""
q"Shut up."
"\"W-W-What..?\""
q"If I didn't answer you the first time, what made you think I'd answer you the second time? Have you got a single brain cell up there?"
"She sighed."
q"It doesn't matter."
"She turned and walked off, her footprints slowly being wiped away by the waves."
"As she took a few steps, she turned around towards me."
q"You. Come. Don't make me repeat myself, alright?"
"Honestly, she sort of bugged me and came off as bratty, but she's probably the best chance I have of learning what was going on with the town."
"I followed her as she walked on the shoreline, just far enough from the waves to stay dry."
"The tension in the air felt so tight I felt as if I could choke on it. Trying to break the tension, I tried to make small talk with her."
"\"I know we got off at the wrong end, but my name is... it's... uh...\""
"I completely forgot about the fact I forgot my name, I made a huge mistake."
"\"I mean, it's nice to meet you. What's your name?\""
q"..."
"Her silence got her message through to me, like an arrow piercing through flesh. She didn't want to talk to me, that was for sure."
"I decided to just give up for now, and continue following her around the shore, the two of us walking in complete silence."
"As we walked on the shore line, I began to notice more about this place I was in."
"The shoreline wrapped around the town in a circle. It looks like I was right earlier, it really is an island."
"The island wasn't particulary big, but was able to accomodate a town, and that was about it. It didn't look like there was anything other than the town on the island."\
"Besides my room, the town square, and the garden, there was quite a bit more on the town I didn't pass through."
"There was what looked like a library, a forest, and a lot more buildings and streets. I tried to identify them, but the girl walked very quickly, and I only got small glimpses of everything else."
"Once we made a full loop around the island, I decided that it was time to ask her another question, even though she was cold towards me earlier."
"\"Say, have you seen anyone else on this island, or has it been just us two?\""
"I expected her to respond to me with silence, and a stare, but instead, she asked me her own question."
q"What do {i}you{/i} think about this island?"
"Maybe she was answering my question, or maybe she was just ignoring me, but I was still confused on how to answer her."
"I honestly had no idea what to say, but I feel like she wouldn't be too happy with me if I started questioning her. But since this might be my only chance to get anything out of her, I just rattled off what was on the top of my head."
"\"You know... I was going to ask you that question. I'm completely clueless about anything on this island. In fact, I don't even know anything about myself.\""
"\"I think I have amnesia or something, but I feel like everything is all just trapped inside me. Matter of fact, I guess you could say I'm on my own island, one inside of my head.\""
"I didn't know where this weird poetic talk came from, but I just went with it."
"\"My name... my age... everything... it's on the mainland, but all I can see is the empty horizon. I can't even be sure if there is anything beyond that horizon, or where that mainland is.\""
q"..."
"She didn't even answer me with any response or follow-up question. Instead, she turned away from me, and gazed into the ocean, like she was lost in thought."
"I decided to do as she did, and also gazed into the ocean. But unlike her, I didn't see what was so special about it."
"It was such a plain scene, every inch of the ocean looked the same, but we stood like that for minutes, maybe hours, I lost track of time."
"Suddenly, she turned away, and continued walking."
q"You. Come."
"I made small comments, and occasionally asked questions. Normally, she would just ignore them, but rarely she'd answer them, or make her own small comment."
"They were as superficial as you could get, and I didn't really get much information out of her about the island, or herself."
"For example, when I asked, \"Small island, huh?\" she just replied with a brief, \"Yeah.\" and continued walking, like she was completely uninterested."
"By the time we finished our second loop around the island, the sunset had finally faded away, and the moonlight reflected onto the sand."
"She turned towards me, and spoke gently, but also firmly."
q"Hm. So it's night time. Thanks, stranger, for this meaningless time. Farewell."
"She turned towards the lights of the town square, and was about to leave, until I caught her attention."
"\"Wait, before you go, let me ask you someting.\""
q"..."
"She responded with the same deathly silence. I could feel the tension build up, as sharp as a knife."
"Regardless, I still mustered up the courage to ask her:"
"\"What's... your name?\""
"She looked at me in surprise, as if she wasn't expecting me to ask her that question."
"For the first time, she showed to me a sign of herself, a more sensitive side. But I could see joy in her eyes, glimmering with the moon's light."
"She looked into the night sky, and stared. I looked up as well."
"The sky glistened with stars, seemingly covering us in a blanket of light, almost like they were smiling at us. It was breathtakingly beautiful."
q"So you asked me what my name was? I'm..." 
"Luna. Call me Luna, I think it's... fitting. Now then, what's your name? I believe you stopped before you told me your name earlier."
"I looked down from the night sky, into the sand. It was all so... empty."
"This island, it was... empty. Everything felt hollow, and I didn't know why. Maybe it was the silence, or the loneliness, but..."
"Just like the sand, everything was just a blur, it all looked the same and felt the same. I felt just like another grain of sand."
"Would it make a difference if that grain of sand was gone? Probably not."
"On this island, we were likely alone, just Luna and me, on this deserted place."
"There was no one esle, no one here for me to depend on, and no one for Luna to depend on."
"Except for each other. We could be... lonely together."
"I raised my eyes back up towards the sky, still glistening bright with stars, surrounding the moon."
"We were going to need each other to survive. For Luna, I wanted to be her everything, I wanted to be the earth that held up her night sky."
"I answered her:"
a"Atlas. My name is Atlas."
"I knew that I screwed it up badly, it was a terrible answer. Still, she seemed to understand what I meant, but didn't show any signs of it."
"Except for a small glimpse of a smile on her face. I blinked, and it was gone."
"She asked me another question:"
l"So, Atlas, when can I see you again?"
a"I... I don't really know, but... I promise that I'll be here tomorrow, as early as possible."
l"Ok."
"She simply nodded, turned, and leaved. Honestly, I wanted to ask another question, but when I turned around, all I saw were light footprints in the sand."
"The gentle night wind laid a light blanket of sand over the footprints, and the beach turned pristine once again, like she'd never been there."
"I felt the land breeze, like a gentle push for me to reach closer to the sea. I made my way closer to the edge of the shore, but..."
"I realised how tired I was. Even though I hadn't really done anything all day, my body ached, and begged to go to sleep."
"Tired, I made my to the garden, so I could go back to my room."
"In the night time, the flowers looked even more pretty, shining from the moonlight."
"I looked at the gazebo, and the layer of dust caught my eye again. I saw light footsteps on the wood floor. There was no ocean to wipe away the footprints."
"It wasn't a dream. She was real. I wasn't really alone here."
"Slowly, I began to feel a warmth in my body, each heartbeat spreading the warmth further into my body."
"I fell to my knees, and a small tear rolled from my eye, and hit the floor. With each tear, another followed... and after that, yet another."
"Small teardrops became a stream of tears. It might've been the relief I felt, but every teardrop felt like another weight lifted from my shoulders."
"At last, after kneeling for I don't know how long, I finally stopped crying, and I carried myself back to my room, mentally weary and tired."
"Unable to lift myself out, I felt myself sink into the bed, and I slowly began to feel everything become a blur, and I fell asleep."
"..."
"..."
q"Atlas..."
"..."
a"Hngh...? What's... what's going on...?"
"I opened my eyes, but all I saw instead of black, was a blur of green, it sort of reminded me of the forest."
a"What...? Where am I? Who's speaking to me? Show yourself!"
"..."
a"Confused and disoriented, I felt my heart begin to race, my palms getting sweatier and sweatier, my body beginning to tremble."
q"Do not be afraid, Atlas. You will be safe here. Come, I have much to tell you, child."
"The voice was soft and gentle, the same way a mother would comfort her daughter. It was nothing like the brash and direct way Luna spoke."
"Still, it didn't help that I still had no idea where I was, or who was talking to me. Nonetheless, I turned to try to face where the voice was coming from."
"..."
"Here, Atlas... don't worry."
"The voice that spoke appeared in front of me, materializing in front of the blur."
"Yet still, I couldn't make what the voice looked like, but I could tell that she was wearing some kind of dress, the rest of her body was just as blurred as the area around me."
a"Who are you, and where am I? Where's the island? How do know my name?"
q"The island... you haven't left the island, Atlas. We're on the island as we speak. I'm afraid I cannot tell you who I am, or why I know your name. Not yet."
a"W-W-What's going on then? This doesn't look like the island!"
q"You're right... Atlas. Do not fear, and do not hesitate, I am not here to hurt you."
q"The island I speak of is not the one which you and the girl live on. No, this is..."
"She paused for a second, before finishing her sentence."
q"I'm afraid I cannot tell you that either, but you will find out in time, do not be worried."
"A million thoughts rushed through my head. Who was this woman, and how did she know my name? And how did I end up here?"
"I looked around me once again, only to find a blur of green. But... where's Luna then? What happened to her? Was she safe?"
"I wanted to ask, but I knew that if I did, all I'd get is probably \"I cannot tell you that yet\" as an answer, so I decided to get as much as I could out of this strange woman."
a"Well, if you can't tell me all these things, then why am I here?"
q"I am here to help you, Atlas."
a"How could you possibly be helping me, when you won't tell me what's going on?"
q"Do not lose patience, Atlas. I am here to deliver you a message, do not take my word for granted."
a"..."
q"Beware of the prison of gold, but love the heart of blue, and you will break through to find the past of the ones you walked along the road with."
a"What is that even supposed to-"
q"The link between us is still weak, we do not have much time. Do not forget my message, and we will meet again."
"As she cut me off, a bright flash began to appear from her body, getting so bright that even the colors of green faded into the whiteness."
"Then as all became white, I closed my eyes to shield myself from the blinding light."
"..."
"I began to feel a warm feeling on my eyes, slowly spreading across my entire face, and then my chest, then slowly reaching throughout my entire body."
"I opened my eyes..."
"And found myself back in my room, flooded by the morning light shining through the window."
"..."
a"Was that all just a dream...? How weird. But what did that woman mean?"
a"\"Beware of the prison of gold, but love the heart of blue, and you will break through to find the past of the ones you walked along the road with.\""
a"..."
"Being on this island without my memory is already weird enough, I don't need anything else making this whole situation more confusing."
"So, I decided to just stop putting my mind on it, and just focus on what I had to do at the moment. And that would be..."
"..."
"I glanced outside the window, remembering the bright light that woke me up from that dream."
a"Wait, hold on, am I forgetting something?"
a"..."
a"Wait! I just remembered! I promised I would meet Luna first thing in the morning!"
"Oh god, what time was it? I looked outside back at the window, trying to guess what time it was based on where the sun was."
"The sun was almost completely out of view from where the window was... which meant... It was almost noon?!"
"My heart skipped a beat, and I jumped out of bed, realising how late I was."
a"Shit! I need to get to the beach {b}now{/b}! What if she already left?"
"Without even changing or freshening up, I sprinted out of my room towards the beach, as fast as I could."
"..."
"She's just staring at me, emotionless. Is she... mad at me?"
a"Hey Luna! Good morning, how are yo-"
l"You're late."
a"Yeah... sorry about that-"
l"You overslept, didn't you?"
a"Huh? How did you know that?"
l"Easy. Your hair's a mess, and you haven't even changed since yesterday. Besides, why else would you be late? It's not like there's anything else to do on the island."
"I sighed."
a"You're right. I overslept, I'm sorry alright?"
l"No."
a"Huh?"
l"It's not alright, if you wanted to give off any sense of basic decency, you'd be here at least an hour before you're supposed to arrive."
a"W-W-W-What?! An hour?! You're joking, right?"
l"Why would I be joking? It only makes sense for you to show up on time if you want to leave a good impression on someone."
a"But you wanted me to show up an hour early? I can't even imagine showing up that early! Wait, hold on..."
a"Does that mean you've been waiting for me the whole morning?"
l"..."
a"Oh... you have, haven't you?"
"Well, she probably shouldn't have been waiting for me that early in the morning, but still..."
"She blushed a little bit, before regaining her composure."
l"It doesn't really matter. I'm going to tell you something, keep it a secret alright? I don't want anyone else to find out."
a"Is there even anyone else for me to tell?"
"She glared at me, her eyes buring with a furious rage, looking deep into my soul."
a"I-I-I mean... please do go on, what did you want to tell me, Luna?"
"She sighed."
l"Well you've probably already figured this out already, but I'm the same as you."
a"Same as me? How?"
l"Do I have to explain {b}everything{/b} to you? I don't have any memory of my life or who I am. It's that simple."
a"So... you don't know where we are either?"
l"Yeah, this island is as confusing as it is to me as it is to you. But unlike you, I have an idea of where I'm going."
a"Hey! What's that supposed to mean?"
"She completely ignored my question."
l"Follow me, I'll show you around the island. Don't get lost, okay?"
"She walked off the beach, and towards the garden."
l"Judging by the footprints you left behind, you've already been here, but this is the garden. As you can see, there's a gazebo, and a bunch of flowers."
"She pointed outwards from the garden into the forest behind the flowers."
l"Hurry up, or else I'll leave you behind."
a"Oh... Okay..."
"She rolled her eyes, as if she was bored out of her mind for being here."
l"And this is... the forest. I don't know what to explain, but in case you're a forest fan, here you go."
"I glanced in between the trees, and I saw a glimpse of a sandy beach."
a"Does the forest connect to the beach?"
"She stared at me in surprise."
l"It does?"
"She pushed past me and stood at the edge of the forest. I followed her and got a clearer view of the beach."
"It looked like we were on some kind of cliff that connected to the beach, about 75 feet up if I guessed."
"Luna regained her composure quickly, the look of shcok on her face quickly replaced by one of smugness."
l"Of course you'd follow me, such a simple observation, and yet you seriously believed that I didn't already know that? My, I must say you're not as bright as I thought."
a"W-W-Wait, what?! You're kidding right? How stupid do you think I am? Hey! Answer me!"
l"Moving on."
"She completely ignored me, and instead headed back towards the garden, a smug smirk on her face the entire time."
l"As you can probably tell, unless I'm mistaken, we're once again back at the garden."
a"So... what was the point of going through the forest, you could've just told me where the forest was, there's a path leading to it!"
l"Hm, yes, it appears like such. That was one of the roads, this is the important one."
"She pointed towards the other path, which led to the town square."
l"Let's go."
a"Hey... Luna?"
l"What is it, I don't have all day, you know?"
a"It's just... do you really know where you're going? I feel like you didn't know where the forest was..."
"She struck a quick glare at me before regaining her composure to her usual annoying and confusing self."
l"Why, of course I did, it's not my fault you're too stupid to catch onto what I'm doing, it's very simple."
a"You're just guiding me around the island, right? What else is there to do?"
l"Well, maybe you'll figure it out when we head towards the town square."
"Wait, town square? She knows where the town square is, yet it felt like she was lost at the forest. Is there really some deeper meaning?"
"Or is she just messing with me?"
l"It was a mistake to bring you along. Hurry up or I'll leave you here alone, go deal with everything on your own, I'm out."
a"W-W-W-Wait!"

